on:
  workflow_dispatch: {}

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anatawa12/something-releaser@v2
      - name: release
        run: |
          set-git-user "anatawa12-bot"
          VERSION="$(get-version)"
          if ! [[ "$VERSION" = *-SNAPSHOT ]]; then
            echo 'VERSION IS NOT SNAPSHOT' >&2
            exit 1
          fi
          VERSION="$(version-unsnapshot "$VERSION")"
          set-version "$VERSION"

          CREATOR_PKG_ROOT="Packages/com.anatawa12.auto-package-installer.creator"

          # create installer unitypackage
          python3 building/build-unitypackage.py installer-template.unitypackage \
            Assets/com.anatawa12.auto-package-installer

          # add to creator unity package
          cp installer-template.unitypackage "$CREATOR_PKG_ROOT/installer-template.unitypackage"
          git add -f "$CREATOR_PKG_ROOT/installer-template.unitypackage"

          # git add to commit version name changes
          git add "$CREATOR_PKG_ROOT/package.json"
          git add "creator/main.mjs"

          git commit -m "$VERSION"
          git tag "v$VERSION"
          git push origin "v$VERSION"

      - name: create package and publish release
        id: mk-pkg
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          VERSION="$(get-version)"
          TAG="v$VERSION"

          # create creator installer unity package
          export USE_LOCAL_PREBUILT=true
          cp building/config.json building/config.json.bak
          sed "s/%%%TAG_NAME%%%/$TAG/" < building/config.json.bak > building/config.json
          node creator/creator.mjs building/config.json installer.unitypackage
          rm building/config.json
          mv building/config.json.bak building/config.json

          # upload release assets
          gh release create "$TAG" \
            "installer-creator.unitypackage" \
            "installer-template.unitypackage" \
            "creator/creator.mjs" \

          tmp="$(mktemp -dt "$(basename $0).$$.XXXXXX")"
          cp installer-template.unitypackage "$tmp/"
          cp building/index.html "$tmp/"
          gh-set-output "tmp" "$tmp"

      - name: prepare next release & push
        run: |
          VERSION="$(get-version)"
          VERSION="$(version-next "$VERSION")"
          set-version "$(version-snapshot "$VERSION")"
          CREATOR_PKG_ROOT="Packages/com.anatawa12.auto-package-installer.creator"
          git rm -f "$CREATOR_PKG_ROOT/installer-template.unitypackage"
          git add "$CREATOR_PKG_ROOT/package.json"
          git add "creator/main.mjs"
          git commit -m "prepare for next version: $VERSION"
          git push && git push --tags

      - name: remove repo
        run: rm -rf * .* || true

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: publish github pages
        env:
          GH_TOKEN: ${{ github.token }}
          tmp: ${{ steps.mk-pkg.outputs.tmp }}
        shell: bash
        run: |
          cp "$tmp/"* .
          git add .
          git commit -m "update"
          git push
