on:
  push:
    tags:
      - v*

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: anatawa12/something-releaser@v2
      - name: release
        run: |
          set-git-user "anatawa12-bot"
          VERSION="$(get-version)"
          if ! [[ "$VERSION" = *-SNAPSHOT ]]; then
            echo 'VERSION IS NOT SNAPSHOT' >&2
            exit 1
          fi
          VERSION="$(version-unsnapshot "$VERSION")"
          set-version "$VERSION"

          git add "Packages/com.anatawa12.auto-package-installer.creator/package.json"
          git commit -m "$VERSION"
          git tag "$VERSION"

      - name: create package and publish release
        id: mk-pkg
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          python3 building/build-unitypackage.py installer-template.unitypackage \
            Assets/com.anatawa12.auto-package-installer
          gh release upload "$TAG" \
            "installer-template.unitypackage"

          tmp="$(mktemp -dt "$(basename $0).$$.XXXXXX")"
          cp installer-template.unitypackage "$tmp/"
          cp building/index.html "$tmp/"
          gh-set-output "tmp" "$tmp"

      - name: prepare next release & push
        run: |
          VERSION="$(get-version)"
          VERSION="$(version-next "$VERSION")"
          set-version "$(version-snapshot "$VERSION")"
          git add "Packages/com.anatawa12.auto-package-installer.creator/package.json"
          git commit -m "prepare for next version: $VERSION"
          git push && git push --tags

      - name: remove repo
        run: rm -rf * .* || true

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: publish github pages
        env:
          GH_TOKEN: ${{ github.token }}
          tmp: ${{ steps.mk-pkg.outputs.tmp }}
        shell: bash
        run: |
          cp "$tmp/"* .
          git add .
          git commit -m "update"
          git push
